<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="2">

  <testsuite name="exampleTest"
    errors="1" failures="0" hostname="" id="" package="exampleTest" skipped="1"
    tests="2" time="0.01100" timestamp="Thu, 18 Jan 2018 23:05:10 GMT">
  
    <testcase name="I can put data in the fields and generate a result" classname="exampleTest" time="0.01100" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Example Test / I can put data in the fields and generate a result]:

  TypeError: Cannot read property &#39;minimumEntry&#39; of undefined
    at Object.I can put data in the fields and generate a result (C:\devmtn\enter-wanted-auto\qa-enter-wanted\nightwatch\tests\exampleTest.js:14:45)
    at Module.call (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
  Error while running [Test / Valid Inputs]:

  TypeError: Cannot read property &#39;errorList&#39; of undefined
    at Object.checkErrors (C:\devmtn\enter-wanted-auto\qa-enter-wanted\nightwatch\test_data\test_functions.js:40:59)
    at Object.Valid Inputs (C:\devmtn\enter-wanted-auto\qa-enter-wanted\nightwatch\tests\test.js:39:19)
    at Module.call (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\DoctaWong\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    </system-err>
  

  
    
    <testcase
      name="I can put bad data in and get the right error message" classname="exampleTest">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
